apiVersion: v1
kind: Service
metadata:
  name: redis-svc
  namespace: mates-app
spec:
  ports:
    - port: 6379
  selector:
    tier: redis

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-dep
  namespace: mates-app
  labels: 
    tier: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: redis
  template:
    metadata:
      labels:
        tier: redis
    spec: 
      containers:
        - name: redis
          image: redis:8-alpine
          ports:
          - containerPort: 6379