apiVersion: v1
kind: Service
metadata:
  name: users-service
  namespace: mates-app
  labels:
    service: users
spec:
  ports:
    - port: 8000
  selector:
    service: users

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
  namespace: mates-app
  labels:
    service: users
spec:
  replicas: 1
  selector: 
    matchLabels: 
      service: users
  template:
    metadata:
      labels:
        service: users
    spec:
      containers:
      - name: users-pod
        image: 3omar0/mates-users:v1.0
        ports:
        - containerPort: 8000
        env:
          - name: SECRET_KEY
            valueFrom:
              secretKeyRef:
                  name: users-secret
                  key: secret_key

          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                  name: users-secret
                  key: postgres_db

          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                  name: users-secret
                  key: postgres_user

          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                  name: users-secret
                  key: postgres_password

          - name: DB_HOST
            valueFrom:
              secretKeyRef:
                  name: users-secret
                  key: db_host

          - name: DB_PORT
            valueFrom:
              secretKeyRef:
                  name: users-secret
                  key: db_port

      initContainers:
      - name: celery-pod
        image: 3omar0/mates-users:v1.0
        command: ["celery"]
        args: ["-A", "users", "worker", "-l", "info"]