apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-celery-deployment
  namespace: mates-app
  labels:
    tier: celery
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: celery
  template:
    metadata:
      labels:
        tier: celery
    spec:
      containers:
      - name: users-pod
        image: 3omar0/mates-users:v1.0
        command: ["celery"]
        args: ["-A", "users", "worker", "-l", "info"]