apiVersion: v1
kind: Service
metadata:
  name: postgres-chat-svc
  labels:
    service: chat-db
spec:
  ports:
    - port: 5432
  selector:
    service: chat-db

---

apiVersion: apps/v1
kind: Deployment
metadata: 
  name: postgres-chat-dep
  labels:
    service: chat-db
spec:
  replicas: 1
  selector:
    matchLabels: 
      service: chat-db
  template:
    metadata:
      labels:
        service: chat-db
    spec:
      containers:
      - name: postgres-db
        image: postgres:15-alpine
        env:
        - name: POSTGRES_DB
          value: mates_chat
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: kirigaya_kazut0
        ports:
        - containerPort: 5432